ST-127 semver compliance
ska-telescope/lmc-base-classes pull request #97
Opened 2019-03-27 14:56 UTC by SKAJohanVenter

@flyingfrog81 @jbmorgado 

A step closer to semver compliance.

In `setup.py` you can only have `N.N.N` - validation regex check updated
(I tried all different combinations and keep running into non semver edge cases)

During the CI build:
- for commits I add `+dev.<SHORT-GIT-HASH>`
- for tags I add `+<SHORT-GIT-HASH>`

Check this CI [build](https://gitlab.com/ska-telescope/lmc-base-classes/pipelines/53883549)
In the artefacts we have:
`lmcbaseclasses-0.0.1+dev.ccdd554d-py2-none-any.whl`

The `setuptools` version is (semver compliant):
`"version": "0.0.1+dev.ccdd554d"`

I also added a step in the `test` stage to install the wheel we just built.

Adding the commit hash:
 - Ensures we install the correct one in the test (there's many others carried over in the cache)
 - Gives you a easy reference should you want to check out the code at that exact point for debugging etc.

2019-03-27 15:35 UTC, flyingfrog81 commented
First of all, thanks for the nicely done PR description

2019-03-27 15:40 UTC, flyingfrog81 commented
If you look at semver specs bullet 10 it says that metadata should only contain alphanumeric characters and hypens, then in the example it uses dot character... cannot understand if the dot is a legal character in the metadata section. 

Maybe it would be safer to have **+dev-hashtag** ? 

```
Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers 
immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII 
alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata SHOULD be 
ignored when determining version precedence. Thus two versions that differ only in the build 
metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-
beta+exp.sha.5114f85.
```

2019-03-27 15:53 UTC, flyingfrog81 commented
sorry for hte noise, but apparently I missed the _dot separated_ part. Turns out I was not the only one as you can see at: https://github.com/semver/semver/issues/293

2019-03-28 11:56 UTC, flyingfrog81 requested changes
At the moment a number of file is stored in the artefacts related to the build jobs, containing different hashes, so it is ambiguous. 

See for example: 
https://gitlab.com/ska-telescope/lmc-base-classes/-/jobs/185292224/artifacts/browse/dist/

2019-03-28 11:57 UTC, flyingfrog81 commented
PAckage is built using the wrong python version. It should be using the same python version used by the test target, which notably is Python3 where this is using Python2

2019-04-01 10:18 UTC, flyingfrog81 approved these changes

2019-04-01 10:19 UTC, flyingfrog81 commented
now everything looks good: 

- Build job is executed on blessed python env
- Tests keep on running ok 
- Only relevant artefacts are published 

this can be merged

2019-04-01 10:28 UTC, SKAJohanVenter commented
Now building a wheel with `semver` compliant versioning.
This wheel is then installed and tested.
Should the pipeline be kicked off with a `git tag` then the wheel is also published to the registry.

2019-04-01 10:31 UTC, merged